locale: 'de_DE'

site:
  name: 'Doctrine 2 standalone Demo'

database:
  dbname: 'demodb'
  user: 'root'
  password: 'password'
  host: 'localhost'
  driver: 'pdo_mysql'
  charset: 'utf8'
  driverOptions:
    1002: 'SET NAMES utf8'
